### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by daijinbiao** [darkhandz/darkhandz.github.io#1]
在吗？

**Comment by darkhandz** [comment]
额，原来跑这边了，你先看看路径吧 [教程](https://github.com/darkhandz/XPS15-9550-Sierra#题外---nvme驱动破解与原生的共存)

**Comment by darkhandz** [comment]
下载后按需要选用，建议用10.12.1的。SSDT-NVME.aml记得放到加载的地方。OZ我不懂。

[NVMe.zip](https://github.com/darkhandz/darkhandz.github.io/files/670891/NVMe.zip)

**Comment by daijinbiao** [comment]
OZ和CLOVER差不多，就是OZ是BIOS层次的，好像现在没法像CLOVER一样kexttopatch，我现在还没用任何DSDT和SSDT的。

**Comment by daijinbiao** [comment]
感谢大神，我去试试
